/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_param_0(void);
extern void test_param_1(void);
extern void test_param_2(void);
extern void test_param_3(void);
extern void test_param_4(void);
extern void test_cmd_echo_1(void);
extern void test_cmd_echo_1b(void);
extern void test_cmd_echo_2(void);
extern void test_cmd_echo_3(void);
extern void test_cmd_echo_4(void);
extern void test_cmd_echo_5(void);
extern void test_cmd_echo_6(void);
extern void test_cmd_echo_7(void);
extern void test_cmd_echo_8(void);
extern void test_cmd_echo_9(void);
extern void test_cmd_echo_10(void);
extern void test_cmd_echo_11(void);
extern void test_cmd_arrows_up(void);
extern void test_cmd_arrows_up_down(void);
extern void test_cmd_pageup_page_down(void);
extern void test_cmd_text_pageup(void);
extern void test_cmd_text_pageup_up(void);
extern void test_cmd_text_delete(void);
extern void test_cmd_insert(void);
extern void test_cmd_tab_1(void);
extern void test_cmd_tab_2(void);
extern void test_cmd_tab_3(void);
extern void test_cmd_tab_4(void);
extern void test_cmd_alias_1(void);
extern void test_cmd_alias_2(void);
extern void test_cmd_alias_3(void);
extern void test_cmd_alias_4(void);
extern void test_cmd_alias_5(void);
extern void test_cmd_var_1(void);
extern void test_cmd_var_2(void);
extern void test_multiple_cmd(void);
extern void test_maxlength(void);
extern void test_ampersand(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "Test.c";
  UnityBegin();
  RUN_TEST(test_param_0, 82);
  RUN_TEST(test_param_1, 85);
  RUN_TEST(test_param_2, 97);
  RUN_TEST(test_param_3, 114);
  RUN_TEST(test_param_4, 132);
  RUN_TEST(test_cmd_echo_1, 146);
  RUN_TEST(test_cmd_echo_1b, 151);
  RUN_TEST(test_cmd_echo_2, 156);
  RUN_TEST(test_cmd_echo_3, 161);
  RUN_TEST(test_cmd_echo_4, 166);
  RUN_TEST(test_cmd_echo_5, 171);
  RUN_TEST(test_cmd_echo_6, 176);
  RUN_TEST(test_cmd_echo_7, 181);
  RUN_TEST(test_cmd_echo_8, 186);
  RUN_TEST(test_cmd_echo_9, 191);
  RUN_TEST(test_cmd_echo_10, 197);
  RUN_TEST(test_cmd_echo_11, 203);
  RUN_TEST(test_cmd_arrows_up, 237);
  RUN_TEST(test_cmd_arrows_up_down, 248);
  RUN_TEST(test_cmd_pageup_page_down, 280);
  RUN_TEST(test_cmd_text_pageup, 295);
  RUN_TEST(test_cmd_text_pageup_up, 310);
  RUN_TEST(test_cmd_text_delete, 328);
  RUN_TEST(test_cmd_insert, 354);
  RUN_TEST(test_cmd_tab_1, 372);
  RUN_TEST(test_cmd_tab_2, 387);
  RUN_TEST(test_cmd_tab_3, 419);
  RUN_TEST(test_cmd_tab_4, 452);
  RUN_TEST(test_cmd_alias_1, 483);
  RUN_TEST(test_cmd_alias_2, 493);
  RUN_TEST(test_cmd_alias_3, 505);
  RUN_TEST(test_cmd_alias_4, 515);
  RUN_TEST(test_cmd_alias_5, 523);
  RUN_TEST(test_cmd_var_1, 531);
  RUN_TEST(test_cmd_var_2, 543);
  RUN_TEST(test_multiple_cmd, 556);
  RUN_TEST(test_maxlength, 567);
  RUN_TEST(test_ampersand, 580);

  return (UnityEnd());
}
